### ISSUE TITLE
Bill Numbers

### ISSUE THREAD

**Issue by joelwool** [aholachek/legislator-scorecard#10]
HW learning/playing with GitHub, adding a 
**TO DO LIST for TEAM PMIC+HW** 
- [x] HW: Add Final Bill #s to the ["FLIPPED" table in Alex spreadsheet](https://docs.google.com/spreadsheets/d/11rK6bUzZpo7CZhOim8jlj8sJ07F33Gr9DIP3GDEOHEI/edit?ts=58c6f182#gid=1725072373) (DONE 3/31)
- [x] HW: Add Final [Bill #s to Alex's spreadsheet](https://docs.google.com/spreadsheets/d/11rK6bUzZpo7CZhOim8jlj8sJ07F33Gr9DIP3GDEOHEI/edit?ts=58c6f182#gid=735319864) (DONE 3/31)
- [x] Update the Bill #s on the Agenda main web page  ([/agenda](http://progressivemass.com/agenda)) (DONE by Jonathan! 3/31)
- [x] Update [the PDF (SHORTLINKED: /legislativeagendapdf](http://progressivemass.com/legislativeagendapdf) (done!) (3/30)

----
What an amazing tool, thank you Alex!

Just a minor note that some of the bill numbers for 2017-2018 are still described using HD and SD -- temporary docket numbers. These should probably be updated before final release. Up to date numbers are listed here and copied below: http://docs.google.com/document/d/1sgJ0ntAq-04meUPrz5WrVueaRVBhBOWKXQxO_nSPtaw/edit

You can tell the difference because a bill would start with "H" rather than "HD"

(Some of the numbers actually need to be updated on the website, too, so I emailed Harmony separately http://www.progressivemass.com/190legislativeagenda). 

H.2172/S.1004: An Act to improve the Commonwealth’s economy with a strong minimum wage and a strong tipped minimum wage  (Donahue-Donnelly) 
Citizen’s Petition: An Initiative Petition for an Amendment to the Constitution of the Commonwealth to Provide Resources for Education and Transportation through an additional tax on incomes in excess of One Million Dollars (Fair Share Amendment) 
H.2365/S.1048: An Act establishing a paid family and medical leave insurance program (Gordon-Spilka) 
S.81: An Act promoting housing and sustainable development (Chandler) 
H.2987/S.619: An Act establishing Medicare for All in Massachusetts (Garlick-Eldridge) 
S.223: An Act modernizing the Foundation Budget for the 21st century (Chang-Diaz) 
H.633/S.681: An Act making public higher education in Massachusetts free for residents of the state (Gentile) / An Act promoting access to debt-free public higher education (Eldridge) 
H.2308/S.791: An Act for justice reinvestment (Keefe - Chang-Diaz) 
H.741/S.819: An Act to eliminate mandatory minimum sentences related to drug offenses (Carvalho-Creem)
H.3269/S.1305: An Act to protect the civil rights and safety of all Massachusetts residents (“Safe Communities Act”) (Matias-Eldridge) 
H.2359/S.777: An Act to reduce the criminalization of poverty (Tyler-Brownsberger) 
H.536/S.499: An Act relative to advancing contraceptive coverage and economic security in our state (ACCESS) (Haddad/Scibak-Chandler) 
H.2091/S.373: An Act automatically registering eligible voters and enhancing safeguards against fraud (Kocot-Creem)
S.1880 An Act creating 21st century Massachusetts clean energy jobs (Pacheco) 
H.2706/S.1864: An Act relative to solar power and the green economy (Mark-Eldridge) 
H.3400/S.1847: An Act clarifying authorities and responsibilities of the Department of Public Utilities (Kulik-Eldridge) 
H.1726/S.1821: An Act to promote green infrastructure, reduce greenhouse gas emissions, and create jobs (Benson) / 
An Act combating climate change (Barrett)

**Comment by harmonywho** [comment]
Pinning Alex's request to me; working on this now. 

>  if you've added the new bill numbers to the cosponsorship csv, can you point me towards the new version (or copy paste the new numbers into [a new column at the very end of this csv](https://docs.google.com/spreadsheets/d/11rK6bUzZpo7CZhOim8jlj8sJ07F33Gr9DIP3GDEOHEI/edit?ts=58c6f182#gid=735319864): https://docs.google.com/spreadsheets/d/11rK6bUzZpo7CZhOim8jlj8sJ07F33Gr9DIP3GDEOHEI/edit?ts=58c6f182#gid=735319864) ?

**Comment by harmonywho** [comment]
@aholachek 
I've updated the column as requested above, on [your version of the Tracking sheet.](https://docs.google.com/spreadsheets/d/11rK6bUzZpo7CZhOim8jlj8sJ07F33Gr9DIP3GDEOHEI/edit?ts=58c6f182#gid=735319864). 
![image](https://cloud.githubusercontent.com/assets/26801934/24574277/0287274c-165e-11e7-9d66-5a2bcd4f0ae3.png)
 I'm happy to share you on the "original" if you want -- but don't want to interrupt the flow. Also/however I did copy/import the relevant sheet from the "original" into "yours", so you have it.  
As noted: 
![image](https://cloud.githubusercontent.com/assets/26801934/24574300/6c185e24-165e-11e7-87a1-c183059a616d.png)

**Comment by harmonywho** [comment]
@aholachek , wasn't sure if this would be helpful to you based on comments, but I updated it anyway: 
Last column (GV) in the ["Cosponsor FLIPPED" tab of 'your' spreadsheet](https://docs.google.com/spreadsheets/d/11rK6bUzZpo7CZhOim8jlj8sJ07F33Gr9DIP3GDEOHEI/edit?ts=58c6f182#gid=1725072373)
![image](https://cloud.githubusercontent.com/assets/26801934/24574524/2f251ff8-1662-11e7-969d-1a54d6ac4705.png)

**Comment by aholachek** [comment]
thank you so much @harmonywho! I've re-run the data-processing scripts, updated the UI, and this should be in the live version shortly

**Comment by joelwool** [comment]
Thank you, Alex @aholachek !
Joel WoolC: (978)697-0361
E: joelwool@gmail.com
Facebook.com/JoelWoolTwitter:@JoelWool






On Sat, Apr 1, 2017 9:34 AM, Alex Holachek notifications@github.com  wrote:
thank you so much @harmonywho! I've re-run the data-processing scripts, updated
the UI, and this should be in the live version shortly
