### ISSUE TITLE
Cosponsor Page: LINKS open in Same Window: CHANGE to open in NEW WINDOW

### ISSUE THREAD

**Issue by harmonywho** [aholachek/legislator-scorecard#12]
![image](https://cloud.githubusercontent.com/assets/26801934/24528673/a5e40b2e-1575-11e7-9a70-a61f4ee55c53.png)

**Comment by harmonywho** [comment]
I Know it's not a bug ... but it's not quite an enhancement? Tag Protocol...

**Comment by aholachek** [comment]
Fixed!
