### ISSUE TITLE
Dylan Fernandes & Kathleen O'Connor Ives -- Score Glitches

### ISSUE THREAD

**Issue by JonathanCohn** [aholachek/legislator-scorecard#13]
Dylan Fernandes shows up on his own page, the homepage, and the index as having a 70% from the last session. He is a freshman and should not have a score for last session. 

Kathleen O'Connor Ives is listed as n/a when she was a regular voting member last session and was scored.

**Comment by aholachek** [comment]
Thanks, corrected, these cases were both tricky to match open states api data with progressive mass data.

**Comment by JonathanCohn** [comment]
Thanks!
