### ISSUE TITLE
Text edits to the co-sponsorship intro (Revised text below)

### ISSUE THREAD

**Issue by JonathanCohn** [aholachek/legislator-scorecard#19]
This session, almost 6,000 pieces of legislation have been filed. Only a few will even make it out of committee, let alone receive a vote. Progressive Mass has identified a suite of bills, across several issue areas, to craft a Progressive Legislative Agenda. These are the bills that can make the most dramatic changes in real people’s lives.  [_Check with Harmony if we can say this last statement is 100% true._]

Cosponsoring legislation is an important way for a Legislator to help put momentum behind certain bills.  It is one of the few signs we have for initial support. 

It’s not enough to push a bill through to passage—but it’s a first step.

**Comment by aholachek** [comment]
Updated, but without the "These are the bills that can make the most dramatic changes in real people’s lives." line right now just to keep things concise.

**Comment by JonathanCohn** [comment]
Thanks!
