### ISSUE TITLE
Cross Checking/Clearing the N/As from "All Legislators" list

### ISSUE THREAD

**Issue by harmonywho** [aholachek/legislator-scorecard#28]
**SEE ALSO: #9**
 - [x] HW to do: audit and make list of the N/As who actually are NOT 'n/as', using the Name Protocols used on [malegislature.gov/Legislators](https://malegislature.gov/Legislators). 
- [x] Alex: Make that fix after hw shares the data

![image](https://cloud.githubusercontent.com/assets/26801934/24581764/8a1a33f2-16ef-11e7-92e8-a89de0c27232.png)
![image](https://cloud.githubusercontent.com/assets/26801934/24581768/b1370c08-16ef-11e7-8fac-9575d7570319.png)

**Comment by harmonywho** [comment]
- [ ] HOUSE "N/a"s have been addressed in this spreadsheet; lmk if you want to move it somewhere else. 

[Copy of Legislation (2017_03) ALEX H Tracking: Cosponsorships, More :(189th, 2017-18)](https://docs.google.com/spreadsheets/d/11rK6bUzZpo7CZhOim8jlj8sJ07F33Gr9DIP3GDEOHEI/edit#gid=0)

![image](https://cloud.githubusercontent.com/assets/26801934/24582159/bbc60fa4-16f7-11e7-9264-1fe50af8343d.png)
![image](https://cloud.githubusercontent.com/assets/26801934/24582165/e387a9b2-16f7-11e7-8142-3052ce77ed43.png)

**Comment by harmonywho** [comment]
- [x] SENATE 'n/as' are checked
THIS DOC: [Copy of Legislation (2017_03) ALEX H Tracking: Cosponsorships, More :(189th, 2017-18)](https://docs.google.com/spreadsheets/d/11rK6bUzZpo7CZhOim8jlj8sJ07F33Gr9DIP3GDEOHEI/edit#gid=1) ... tab as shown.
The only thing to maybe pay closer attn to is K O'Connor Ives -- It's not clear to me whether the 'official' cell should be 'O'Connor Ives, Kathleen" or "Ives, Kathleen O'Connor"
![image](https://cloud.githubusercontent.com/assets/26801934/24582221/ec85eb0e-16f8-11e7-8aaa-a37ea7e9db78.png)

**Comment by aholachek** [comment]
I'm pretty sure all the errors in house + senate have been corrected.
