### ISSUE TITLE
CoSponsor List: Remove "Const. Amdt" 

### ISSUE THREAD

**Issue by harmonywho** [aholachek/legislator-scorecard#29]
As before (probably snuck back in during other tweaks)

![image](https://cloud.githubusercontent.com/assets/26801934/24582270/bdd0aa14-16f9-11e7-829c-6dcae2ad2c17.png)

**Comment by aholachek** [comment]
hi @harmonywho 
I will remove it by deleting the corresponding row in the cosponsorship spreadsheet.
This is a good example of the fact that I'm going to avoid editing the data as much as possible -- if it's in the spreadsheet, it will go in the app. So the easiest thing for me to do would be if you made sure rows of data that shouldn't be in the app, aren't in the cosponsorship spreadsheet at all.
