### ISSUE TITLE
189th HOUSE Platform Plank

### ISSUE THREAD

**Issue by harmonywho** [aholachek/legislator-scorecard#3]
See [Column N for the Platform Plank bucket](https://docs.google.com/spreadsheets/d/1_4DvG2AAflZZBwH-0Yp1GjaKnK-7Lg85ICcP4RI4gdY/edit#gid=1211874272)

QUESTION: would it be feasible or confusing for one Vote to "live" under two categories? 

For example, a bill prohibiting undoc'd immigrants from living in PUblic Housing is both a "Social Justice" thing (xenophobia) and a Economic Justice thing (housing policy). Let me know if double dipping on platform is possible or nah. 

![image](https://cloud.githubusercontent.com/assets/26801934/24525437/3f29be04-1568-11e7-89f4-ba153f0c72fc.png)

**Comment by aholachek** [comment]
Definitely possible, that makes sense. Could you separate the different platforms with just a comma, in the same cell? it will be easier to parse that way.

**Comment by harmonywho** [comment]
Yes, can do that -- will go revisit for any Doubling Ups.

**Comment by harmonywho** [comment]
DONE for House/this one. Going to do senate
