### ISSUE TITLE
N/a on the last Senate roll call vote

### ISSUE THREAD

**Issue by JonathanCohn** [aholachek/legislator-scorecard#30]
All senators seem to have their vote listed as n/a for the last vote in the scorecard. Any idea why?

**Comment by aholachek** [comment]
Hmm I see N/A not for the last vote but third to last:
<img width="968" alt="screen shot 2017-04-02 at 9 34 40 pm" src="https://cloud.githubusercontent.com/assets/3680488/24592966/3628dfde-17ec-11e7-9e1c-0254da3374ab.png">

Something must have gone wrong when I re-ran the parsing scripts today, I'll look into it now.

**Comment by JonathanCohn** [comment]
That's the House. Thanks for catching that one, though!

**Comment by aholachek** [comment]
Ah that one was a result of 543 somehow going back to 453 in my spreadsheet... The one you pointed out was a result of the bill number being written as 2451 instead of S.2451 in the vote descriptions spreadsheet, it's been fixed.

**Comment by JonathanCohn** [comment]
Thanks!
