### ISSUE TITLE
"This Data Isn't Available Yet" 

### ISSUE THREAD

**Issue by harmonywho** [aholachek/legislator-scorecard#7]
**Language edit: **  Update _"Not available"_ to something a little more dead-endy. ... and set up expectations about when it WILL be (since we really don't LIVE update the Scorecard -- it kinda comes out at the end all at once -- bec we're balancing lots of possibilities--dont want to overscore one thing, etc) . ...

This is not the language, but something along these lines: 
"Final scorecards are released at the end of the session; mid-session updates will come out in (JAN/FEB 2018)". 
**ENHANCEMENT**
^^ And then also let's you, me, PMIC talk about what are possibilities for tracking that isn't the scorecard per se but "Of interest" .... 
-- there are LEGISLATIVE and procedural considerations here (nothing is straightforward) (Them)
-- coding/app considerations (I have no idea) (You)
-- Editorial consideration (Us)-- not every vote is Of Interest; not every vote that seems on its face "Of Interest" IS of interest... etc. 
^^^this maybe belongs in its own ticket later. But for now...

**Comment by aholachek** [comment]
Done!
<img width="963" alt="screen shot 2017-03-31 at 8 54 41 am" src="https://cloud.githubusercontent.com/assets/3680488/24551222/b599b9d6-15ef-11e7-8a50-0571152bbced.png">
